### PR TITLE
Fix for issue #5 - Cannot load thumbnail from sorl.thumbnail

### PR DESCRIPTION
**Pull request by mihaisucan**
This is the fix for issue #5. Please let me know if further changes are need before you accept the pull request. Thank you very much for your work!

### CODE REVIEW

**Comment by mihaisucan** [comment]
Cody: I just pushed more changes. I added tests for `load` and `import` and I created an app that mimics the same situation with easy_thumbnails and sorl.thumbnail. I had to do more changes in the `get_library` method to fix the regressions I caused with my quick fix yesterday.

Please let me know if this works for you or if I need to make more changes. Thank you!

**Comment by codysoyland** [comment]
Awesome, the tests pass and it looks good. Thanks for the contribution!

**Comment by mihaisucan** [comment]
Thank you! Looking forward to see this updated code in the pip/easy_install distributions of django-smart-load-tag.

**Comment by codysoyland** [comment]
I sometimes forget that step. Just uploaded to PyPI so pip/easy_install should reflect the latest changes now.

**Comment by mihaisucan** [comment]
Thank you!

**Comment by timmyomahony** [comment]
Just in case anyone comes to this curious how to implement this in a template: https://gist.github.com/2843120

**Pull request merged**
